name: Computer Testing

on: push

jobs:
  test-computer:
    name: Test Computer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        # Put your testing script or commands here
        # For example, you could run a Python script:
        # python tests.py
        # Or execute a shell script:
        # sh run_tests.sh
